plugins {
    id("com.android.application")
}

android {
    namespace = "com.shinian.pay"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.shinian.pay"
        minSdk = 21
        targetSdk = 35
        versionCode = 15
        versionName = "3.1"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("${projectDir}/keystore/keystore.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: project.hasProperty("KEYSTORE_PASSWORD") ? project.property("KEYSTORE_PASSWORD") : ""
            keyAlias System.getenv("KEY_ALIAS") ?: (project.hasProperty("KEY_ALIAS") ? project.property("KEY_ALIAS") : "")
            keyPassword System.getenv("KEY_PASSWORD") ?: (project.hasProperty("KEY_PASSWORD") ? project.property("KEY_PASSWORD") : "")
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

configurations.configureEach {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    // 本地 libs
    implementation fileTree(include: ['*.aar', '*.jar'], dir: './libs')

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation "androidx.core:core-ktx:1.13.0"

    // Material UI
    implementation 'com.google.android.material:material:1.9.0'

    // OkHttp 统一用 4.x（Kotlin 版本）
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    // ZXing
    implementation 'com.google.zxing:core:3.5.3'

    // WorkManager
    implementation "androidx.work:work-runtime:2.9.1"

    // Test
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'

}